In [1]:
import pandas as pd
from glob import glob

In [2]:
files = glob('dataset/*.csv')
files

['dataset/ai4i2020.csv',
 'dataset/tabular-actgan-6511394f6ba2208754b85be6-data_preview_1.csv.csv',
 'dataset/predictive_maintenance_dataset.csv',
 'dataset/Wafer_15010_130532.csv',
 'dataset/predictive_maintenance.csv']

In [3]:
df1 = pd.read_csv(files[0])
print(files[0])
df1

dataset/ai4i2020.csv

,UDI,Product ID,Type,Air temperature [K],Process temperature [K],Rotational speed [rpm],Torque [Nm],Tool wear [min],Machine failure,TWF,HDF,PWF,OSF,RNF
0,1,M14860,M,298.1,308.6,1551,42.8,0,0,0,0,0,0,0
1,2,L47181,L,298.2,308.7,1408,46.3,3,0,0,0,0,0,0
2,3,L47182,L,298.1,308.5,1498,49.4,5,0,0,0,0,0,0
3,4,L47183,L,298.2,308.6,1433,39.5,7,0,0,0,0,0,0
4,5,L47184,L,298.2,308.7,1408,40.0,9,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,M24855,M,298.8,308.4,1604,29.5,14,0,0,0,0,0,0
9996,9997,H39410,H,298.9,308.4,1632,31.8,17,0,0,0,0,0,0
9997,9998,M24857,M,299.0,308.6,1645,33.4,22,0,0,0,0,0,0
9998,9999,H39412,H,299.0,308.7,1408,48.5,25,0,0,0,0,0,0
9999,10000,M24859,M,299.0,308.7,1500,40.2,30,0,0,0,0,0,0

In [4]:
df2 = pd.read_csv(files[1])
print(files[1])
df2

dataset/tabular-actgan-6511394f6ba2208754b85be6-data_preview_1.csv.csv

,UDI,Product ID,Type,Air temperature [K],Process temperature [K],Rotational speed [rpm],Torque [Nm],Tool wear [min],Machine failure,TWF,HDF,PWF,OSF,RNF
0,2785,L52016,L,302.1,311.1,1254,61.2,64,1,0,1,0,0,0
1,333,L47564,M,296.5,307.1,1770,52.7,144,0,0,0,0,0,0
2,3765,M17806,L,300.6,309.3,1582,38.7,115,0,0,0,0,0,0
3,8414,L47898,L,298.7,309.6,1382,65.8,100,0,0,0,0,0,0
4,993,L48952,L,298.5,308.0,1425,40.3,144,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,891,L50992,M,298.8,309.7,1863,22.3,167,0,0,0,0,0,0
4996,6740,L54859,L,300.5,310.6,1410,55.9,17,0,0,0,0,0,0
4997,324,L55874,L,298.4,308.5,1661,53.1,174,0,0,0,0,0,0
4998,581,L50227,M,301.6,308.8,1406,30.7,63,0,0,0,0,0,0
4999,3656,H34510,L,303.5,309.7,1418,55.5,200,1,0,0,1,0,0

In [5]:
df3 = pd.read_csv(files[2])
print(files[2])
df3

dataset/predictive_maintenance_dataset.csv

,date,device,failure,metric1,metric2,metric3,metric4,metric5,metric6,metric7,metric8,metric9
0,1/1/2015,S1F01085,0,215630672,55,0,52,6,407438,0,0,7
1,1/1/2015,S1F0166B,0,61370680,0,3,0,6,403174,0,0,0
2,1/1/2015,S1F01E6Y,0,173295968,0,0,0,12,237394,0,0,0
3,1/1/2015,S1F01JE0,0,79694024,0,0,0,6,410186,0,0,0
4,1/1/2015,S1F01R2B,0,135970480,0,0,0,15,313173,0,0,3
...,...,...,...,...,...,...,...,...,...,...,...,...
124489,11/2/2015,Z1F0MA1S,0,18310224,0,0,0,10,353705,8,8,0
124490,11/2/2015,Z1F0Q8RT,0,172556680,96,107,4,11,332792,0,0,13
124491,11/2/2015,Z1F0QK05,0,19029120,4832,0,0,11,350410,0,0,0
124492,11/2/2015,Z1F0QL3N,0,226953408,0,0,0,12,358980,0,0,0
124493,11/2/2015,Z1F0QLC1,0,17572840,0,0,0,10,351431,0,0,70000

In [6]:
df4 = pd.read_csv(files[3])
print(files[3])
df4

dataset/Wafer_15010_130532.csv

,Unnamed: 0,Sensor-1,Sensor-2,Sensor-3,Sensor-4,Sensor-5,Sensor-6,Sensor-7,Sensor-8,Sensor-9,...,Sensor-581,Sensor-582,Sensor-583,Sensor-584,Sensor-585,Sensor-586,Sensor-587,Sensor-588,Sensor-589,Sensor-590
0,Wafer-800,3002.22,2462.06,2202.1222,1833.3772,1.8005,100,95.8500,0.1242,1.5173,...,NaN,NaN,0.5021,0.0071,0.0024,1.4182,0.0545,0.0184,0.0055,33.7876
1,Wafer-500,3047.28,2186.06,2235.0556,1302.6607,1.6347,100,109.9856,0.1230,1.4619,...,NaN,NaN,0.4998,0.0131,0.0033,2.6229,0.0222,0.0182,0.0060,81.9472
2,Wafer-501,3076.81,2158.75,2208.2334,1517.0152,1.0980,100,110.1900,0.1247,1.4357,...,0.0090,64.2405,0.5016,0.0152,0.0040,3.0319,0.0465,0.0299,0.0090,64.2405
3,Wafer-502,2951.62,2511.92,2253.5111,1397.5060,0.9660,100,109.7611,0.1210,1.5527,...,0.0081,0.0000,0.4953,0.0105,0.0037,2.1266,-0.0012,0.0252,0.0081,0.0000
4,Wafer-503,2930.42,2505.17,2235.0556,1302.6607,1.6347,100,109.9856,0.1230,1.4588,...,NaN,NaN,0.4958,0.0111,0.0033,2.2296,-0.0012,0.0252,0.0081,0.0000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
96,Wafer-595,2989.44,2487.66,2201.0667,880.2317,1.4148,100,106.5478,0.1211,1.5301,...,NaN,NaN,0.4933,0.0126,0.0032,2.5579,0.0227,0.0149,0.0052,65.4831
97,Wafer-596,2996.89,2492.40,2217.8667,1275.0917,1.5487,100,105.2933,0.1230,1.5455,...,NaN,NaN,0.5071,0.0123,0.0038,2.4294,0.0227,0.0149,0.0052,65.4831
98,Wafer-597,2990.85,2485.99,2167.9444,861.8041,1.4140,100,106.6033,0.1243,1.4647,...,NaN,NaN,0.5015,0.0130,0.0042,2.5884,0.0227,0.0149,0.0052,65.4831
99,Wafer-598,3059.43,2473.55,2214.9333,1663.7024,1.0203,100,100.4456,0.1247,1.4262,...,0.0114,108.6076,0.4973,0.0073,0.0017,1.4716,0.0300,0.0326,0.0114,108.6076
100,Wafer-599,3024.54,2420.25,2167.9444,861.8041,1.4140,100,106.6033,0.1243,1.4849,...,NaN,NaN,0.5006,0.0068,0.0018,1.3667,0.0300,0.0326,0.0114,108.6076

In [7]:
df4 = pd.read_csv(files[4])
print(files[4])
df4

dataset/predictive_maintenance.csv

,UDI,Product ID,Type,Air temperature [K],Process temperature [K],Rotational speed [rpm],Torque [Nm],Tool wear [min],Target,Failure Type
0,1,M14860,M,298.1,308.6,1551,42.8,0,0,No Failure
1,2,L47181,L,298.2,308.7,1408,46.3,3,0,No Failure
2,3,L47182,L,298.1,308.5,1498,49.4,5,0,No Failure
3,4,L47183,L,298.2,308.6,1433,39.5,7,0,No Failure
4,5,L47184,L,298.2,308.7,1408,40.0,9,0,No Failure
...,...,...,...,...,...,...,...,...,...,...
9995,9996,M24855,M,298.8,308.4,1604,29.5,14,0,No Failure
9996,9997,H39410,H,298.9,308.4,1632,31.8,17,0,No Failure
9997,9998,M24857,M,299.0,308.6,1645,33.4,22,0,No Failure
9998,9999,H39412,H,299.0,308.7,1408,48.5,25,0,No Failure
9999,10000,M24859,M,299.0,308.7,1500,40.2,30,0,No Failure